(define-module (lklee artifact)
  #:use-module (haunt artifact)
  #:export (pdflatex-artifact))

(define (pdflatex-artifact tex-file-dir tex-file-name)
  (make-artifact (string-append tex-file-dir "/" tex-file-name)
                 (lambda (output)
                   (define cur-dir (getcwd))
                   (chdir (string-append "../site/" tex-file-dir))
                   ;(display (getcwd))
                   (system* "latexmk" tex-file-name)
                   (chdir cur-dir)
                   ))
  )
