baseURL = 'http://lklee.dev/'
languageCode = 'en-us'
title = 'lklee.dev'
[markup.goldmark.renderer]
  unsafe = true
[params]
  author = "Loong Kuan Lee"
[menu]
  [[menu.main]]
    name = "lklee"
    url = "/"
    weight = 1
  [[menu.pub]]
    name = "publications"
    url = "/pubs/"
    weight = 2
