#+hugo_base_dir: ./
#+hugo_front_matter_format: yaml

* DONE About
:PROPERTIES:
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: about
:END:
#+begin_src yaml :front_matter_extra t
links:
  email: ["mailto:mail@lklee.dev", "mail@lklee.dev"]
  github: ["https://github.com/lklee9", "lklee9"]
  gitlab: ["https://gitlab.com/lklee", "lklee"]
#+end_src
My name is Loong Kuan Lee. I am currently a PhD candidate at Monash university awaiting the results for my thesis. My areas of interest include concept drift and probabilistic graphical models.
* Blog :@blog:
:PROPERTIES:
:EXPORT_HUGO_SECTION: blog
:END:
* Publications
:PROPERTIES:
:EXPORT_HUGO_SECTION: pubs
:END:
** DONE lee2023
:PROPERTIES:
:EXPORT_FILE_NAME: lee23
:END:
#+begin_src yaml :front_matter_extra t
status: accepted
title: Computing Divergences between discrete decomposable models
author:
  - family: Lee
    given: Loong Kuan
  - family: Piatkowski
    given: Nico
  - family: Petitjean
    given: François
  - family: Webb
    given: Geoffrey I.
venue: Proceedings of the AAAI Conference on Artificial Intelligence
# DOI: 10.1007/s10618-018-0554-1
year: 2023
type: paper-conference
links:
  - name: ar𝚾iv
    link: https://arxiv.org/abs/2112.04583
  - name: code
    link: https://gitlab.com/lklee/comp-div-dm
#+end_src
There are many applications that benefit from computing the exact
divergence between 2 discrete probability measures, including machine
learning. Unfortunately, in the absence of any assumptions on the
structure or independencies within these distributions, computing the
divergence between them is an intractable problem in high dimensions. We
show that we are able to compute a wide family of functionals and
divergences, such as the alpha-beta divergence, between two decomposable
models, i.e~chordal Markov networks, in time exponential to the
treewidth of these models. The alpha-beta divergence is a family of
divergences that include popular divergences such as the
Kullback-Leibler divergence, the Hellinger distance, and the chi-squared
divergence. Thus, we can accurately compute the exact values of any of
this broad class of divergences to the extent to which we can accurately
model the two distributions using decomposable models.
** DONE webb18
:PROPERTIES:
:EXPORT_FILE_NAME: webb18
:END:
#+begin_src yaml :front_matter_extra t
status: published
title: Analyzing concept drift and shift from sample data
author:
  - family: Webb
    given: Geoffrey I.
  - family: Lee
    given: Loong Kuan
  - family: Goethals
    given: Bart
  - family: Petitjean
    given: François
venue: Data Mining and Knowledge Discovery
DOI: 10.1007/s10618-018-0554-1
year: 2018
type: article-journal
links:
  - name: ResearchGate
    link: https://www.researchgate.net/publication/323702657_Analyzing_concept_drift_and_shift_from_sample_data
  - name: code
    link: https://github.com/lklee9/DriftMapper
#+end_src
Concept drift and shift are major issues that greatly affect the
accuracy and reliability of many real-world applications of machine
learning. We propose a new data mining task, concept drift
mapping—the description and analysis of instances of concept drift
or shift. We argue that concept drift mapping is an essential
prerequisite for tackling concept drift and shift. We propose tools
for this purpose, arguing for the importance of quantitative
descriptions of drift and shift in marginal distributions. We
present quantitative concept drift mapping techniques, along with
methods for visualizing their results. We illustrate their
effectiveness for real-world applications across energy-pricing,
vegetation monitoring and airline scheduling.
